### ISSUE TITLE
It's not clear in the README how y'all recommend to invoke this tool.

### ISSUE THREAD

**Issue by dhnaranjo** [Loomly/s3_asset_deploy#26]
Hello! So, I dunno, maybe I'm a fraud, but I feel like there's some info missing from your README describing how and when you actually use this tool. Maybe something like taking the entire contents of the https://github.com/Loomly/s3_asset_deploy#usage section and dropping it into a Rake task, something like this:

```
# lib/tasks/assets.rb

  namespace :assets do
    desc "Deploy assets to S3"
    task :deploy => :environment do
      manager = S3AssetDeploy::Manager("my-s3-bucket")
        manager.deploy do
          # Perform deploy to web instances in this block
        end
    end
  end
```

And then an example of extending your existing precompilation call to `bin/rails assets:precompile assets:deploy`.

Maybe this is obvious to y'all on account of building the thing, but I spent a decent amount of time trying to understand if this was all occurring automatically, or if this config was in an initializer, or what. It was only when I read the https://github.com/AssetSync/asset_sync documentation, figuring your tool might work similarly since it is informed by that one, that I reached my current assumption. I would not mind submitting a lil documentation updating PR but, honestly, I'm still not sure if this is the sensible way to use the tool.

**Comment by summera** [comment]
@dhnaranjo thanks for the feedback! Super helpful. Using a rake task is exactly what we do now. Something like:

```ruby
# lib/tasks/deploy.rake

require "s3_asset_deploy"

namespace :deploy do
  task precompile: :environment do
    puts "Precompiling assets..."
    sh("RAILS_ENV=production DEVISE_SECRET_KEY='secret key' SECRET_KEY_BASE='secret key' bundle exec rake assets:precompile")
  end

  task clobber_assets: :environment do
    puts "Clobbering assets..."
    sh("RAILS_ENV=production DEVISE_SECRET_KEY='secret key' SECRET_KEY_BASE='secret key' bundle exec rake assets:clobber")
  end

  task :production do
    Rake::Task["deploy:precompile"].invoke

    manager = S3AssetDeploy::Manager("my-s3-bucket")
    manager.deploy do
      # Perform deploy to web instances in this block
    end
    
    Rake::Task["deploy:clobber_assets"].invoke # <-- if you are running on CI where the precompiled assets dir is ephemeral, this may be unnecessary
  end 
end

```

Your suggestion for improving the documentation is great and I'd be happy to update the README with more information.

We use CircleCI for CI/CD and this is where we run our rake task to deploy. I can also add some info to the README about how we use CircleCI for caching compiled assets to speed up compilation time if that would be helpful?

**Comment by dhnaranjo** [comment]
Hello! The example you've provided in that snippet is totally sufficient for my understanding. Having a CircleCI example wouldn't hurt none, tho. It'd be nice to have the outlines of a full implementation, even if it's just an example rather than like, firm instructions.

**Comment by summera** [comment]
@dhnaranjo done in https://github.com/Loomly/s3_asset_deploy/pull/27 👍
